### ISSUE TITLE
希望Java.md可以拆分一下

### ISSUE THREAD

**Issue by chenshijin1** [Seazean/JavaNote#4]
非常感谢up做的如此精美的笔记！
给个小建议，比如Java.md文档，Java：JavaSE、JVM、Algorithm、Design Pattern
可以拆成一个一个小模块

**Comment by Seazean** [comment]
是的  确实有点大，如果阅读需要可以clone后自行更改一下，文件太大会卡顿。作者最近刚换了电脑，不卡了，所以就没在拆分

**Comment by f4cklangzi** [comment]
笔记非常棒，就是太长了，希望能够按照每个知识点拆分成多个小的文档，这样需要查看某个知识点的内容就可以去对应的文件中去找，看起来会方便很多，也不会那么卡了。自己拆分的话就没办法看到up主最新的更新笔记了。

**Comment by Seazean** [comment]
> 笔记非常棒，就是太长了，希望能够按照每个知识点拆分成多个小的文档，这样需要查看某个知识点的内容就可以去对应的文件中去找，看起来会方便很多，也不会那么卡了。自己拆分的话就没办法看到up主最新的更新笔记了。

同学好，谢谢提议，我是有这个计划的，但是目前自己正在找实习，等着实习稳定后，会慢慢修改，设置目录，拆分文件，让笔记的可读性变强
